/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eklvaya;

/**
 *
 * @author Ashu
 */
public class How88 extends javax.swing.JFrame {

    /**
     * Creates new form How88
     */
    public How88() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("-----------------------------");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, 20));

        jLabel16.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel16.setText("DL+M ÒJGDF\\ VF56M JW] G[ JW] ;DI JFTM ;F\\E/JFDF\\ 5;FZ YFI K[P");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jButton9.setText("Next");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel17.setText("SM.56 XaNMG[ IMuIZLT[ ;F\\E/JF DF8[ V[ XaNM p5Z wIFG VF5J] VTL H~ZL K[P");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        jLabel18.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel18.setText(";FR] VG[ ;FR] ;F\\E/J] VTL H~ZL K[P ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jLabel19.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel19.setText("S,F;~D DF\\ XL1FSMGF XaNM p5Z 5]ZT] wIFG VF5MP");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jLabel20.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel20.setText("XL1FSM £FZF AM,FI[,F XaNM DGDF AM,MP ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 30));

        jLabel22.setFont(new java.awt.Font("TERAFONT-CHANDAN", 1, 36)); // NOI18N
        jLabel22.setText(" ;F\\E/JFGL S,F");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 230, 40));

        jLabel40.setText("=>");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 30));

        jLabel41.setText("=>");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 30));

        jLabel43.setText("=>");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 80, 30));

        jLabel45.setText("=>");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        jLabel23.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/ConvertedImage/How50.jpg"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 370, 430));

        jLabel46.setText("=>");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 30));

        jLabel21.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel21.setText("TD[ ;FR] ;F\\E/L XSXM TMH ;FR] ;DÒ XSM KM VG[ TMH ;FR] AM,L  XSM KM V[8,[ S[");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        jLabel24.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel24.setText(";FD[JF/L jISTL AM,TL CMI tIFZ[ T[G[ 8MSJL GCLP VYJF TM  JrR[ JrR[ AM,J] GCLP");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jLabel44.setText("=>");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/background1090x515.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        jLabel25.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel25.setText(" ;FD[JF/L jISTL AM,TL CMI tIFZ[ T[G[ 8MSJL GCLP VYJF TM  JrR[ JrR[ AM,J] GCLP");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        How87 a = new How87();
        this.dispose();
        a.setTitle("How to..");
        a.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        How89 a = new How89();
        this.dispose();
        a.setTitle("How To..");
        a.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(How88.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(How88.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(How88.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(How88.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new How88().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    // End of variables declaration//GEN-END:variables
}
