/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eklvaya;

/**
 *
 * @author Ashu
 */
public class STD_Art extends javax.swing.JFrame {

    /**
     * Creates new form STD_Art
     */
    public STD_Art() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel5.setText("EUJFG[ VF56G[ SM.G[ SM. S,F E[8 DF\\ VF5L K[P");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel3.setText("VF56F AWF GL V\\NZ V[S S,FSFZ K]5FI[,M CMI K[P");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel6.setText("SM. jISTL ;FZ] 5[g\\8LU AGFlJ XS[4SM. ;FZM VELGI SZL XS[ K[4SM. ;FZF ULTM UF. XS[ K[P");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel7.setText("VF56L V\\NZ K]5FI[,L S,F VMG[ VF56[ ACFZ ,FJJL HM.V[P");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel8.setText("VF56L H[J0L H é\\DZGL 85];[GF ccTFZS DC[TF SF é<8F RxDFcc DF\\ VELGI SZ[ K[P");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel11.setText("T[DG[ 5MTFGL VELGI S,FGL SFZJ[ DM8F S,FSFZM ;FY[ SFD SZJFGM DMSM D/[ K[P VG[ N[X  N]GLIFDF HF6LTF AG[ K[P");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("TERAFONT-CHANDAN", 1, 36)); // NOI18N
        jLabel4.setText("DFZ[ S,FSFZ AGJ] K[P");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/ConvertedImage/artPic.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/ConvertedImage/29.jpg"))); // NOI18N
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 200));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/ConvertedImage/28.jpg"))); // NOI18N
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 200, 200));

        jButton6.setText("HOME");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        jButton7.setText("NEXT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 75, -1));

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("TERAFONT-CHANDAN", 0, 24)); // NOI18N
        jLabel9.setText("SM. ;FZF JFÒ+F JUF0L XS[P");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, -1));

        jLabel24.setText("=>");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, 30));

        jLabel25.setText("=>");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 30));

        jLabel26.setText("=>");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 70, 30));

        jLabel27.setText("=>");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, 30));

        jLabel28.setText("=>");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, 30));

        jLabel29.setText("=>");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, 30));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-----------------------------------------------------------------");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 520, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eklvaya/background1090x515.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1090, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Home a =new Home();
        this.dispose();
        a.setTitle("Home");
        a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        STD_BusinessMan a =new STD_BusinessMan();
        this.dispose();
        a.setTitle("Become a BusinessMan");
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Student a =new Student();
        this.dispose();
        a.setTitle("Student");
        a.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STD_Art.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STD_Art.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STD_Art.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STD_Art.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STD_Art().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
